# Generated by Django 5.0.2 on 2024-03-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZenSpelling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZenSpelling.course')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='ZenSpelling.question')),
                ('questionSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZenSpelling.questionset')),
            ],
        ),
    ]
