# Generated by Django 5.0.2 on 2024-02-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZenSpelling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='option_text',
            new_name='options_text',
        ),
    ]
